config/routes.rb
Elegan::Application.routes.draw do

  get 'welcome/index'
  get 'welcome/about'

  root 'welcome#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :post
  has_one :picture, as: :imageable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_one :category
  has_many :comments
  has_many :pictures, as: :imageable
  has_and_belongs_to_many :tags

  scope :last_five, -> { last(5) }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @last_five_posts = Post.last_five
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header>
  <%= link_to 'Home', root_path%>
   | <%= link_to 'About', welcome_about_path %>
   <%= link_to 'Add Post', '#', class: 'right' %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elegan</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/flash' %>

<div class="contents">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquam, neque nec egestas rhoncus, elit risus mattis ligula, at mattis velit lacus eget urna. Etiam in turpis in ipsum mollis pretium id sed diam. Sed at arcu in est euismod varius. Sed id augue et nulla dictum pellentesque. In condimentum viverra velit, sit amet semper erat rutrum vel. Integer dictum neque a augue condimentum sollicitudin. Vestibulum rhoncus dolor sed arcu euismod, sed tincidunt magna fermentum. Donec eros erat, consectetur nec elit vel, facilisis vulputate eros. Sed convallis ante id viverra dignissim.
</p>

<p>
  Aenean pharetra laoreet leo, at posuere lorem ultrices et. Suspendisse a orci nunc. Suspendisse luctus, lorem sed convallis blandit, tellus dui congue nisl, a porta sapien ipsum a erat. Cras vestibulum sapien ut erat laoreet facilisis. Sed porta dolor massa, quis aliquet dui pharetra vel. Fusce neque urna, tempor at risus ut, rutrum aliquam purus. Maecenas vitae lorem interdum, congue ante vitae, posuere urna. Etiam porttitor orci in vestibulum tincidunt. Duis dui eros, malesuada nec rhoncus at, facilisis sed tortor. Nam fermentum vel elit ut blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum iaculis magna urna, in suscipit eros convallis sit amet. Duis mattis, ipsum quis cursus bibendum, dolor dolor semper nisi, nec venenatis nibh leo vel nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus.
</p>

<p>
  Phasellus elit purus, varius quis ligula at, pharetra tincidunt velit. Integer dignissim, augue sed aliquam auctor, turpis dui tincidunt dolor, sed dignissim purus leo eget tortor. In diam est, tempor quis iaculis in, tristique id leo. Curabitur non urna erat. Curabitur suscipit eleifend fringilla. Vivamus sed dolor commodo ante malesuada bibendum sed porta urna. Ut mattis scelerisque eros ac rutrum.
</p>

app/views/welcome/index.html.erb
<h1>Elegan Blog</h1>

<div class="left liquid">
  <h3>Last Posts</h3>

  <ul>
  <% @last_five_posts.each do |post| %>
    <li><%= link_to post.title, '#' %></li>
  <% end%>
  </ul>
</div>

<div class="right liquid">
  <h3>Last Comments</h3>
</div>